site_name: COMPAS ThreeJS Docs
# site_url: None

repo_name: COMPAS ThreeJS
repo_url: https://github.com/compas-dev/compas_threejs/

extra:
    # homepage: None
    version:
        provider: mike

theme:
    name: material
    palette:
        # Palette toggle for light mode
        - scheme: default
          primary: indigo
          accent: indigo
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode
        # Palette toggle for dark mode
        - scheme: slate
          primary: indigo
          accent: indigo
          toggle:
              icon: material/brightness-4
              name: Switch to light mode
    font:
        text: Roboto
        code: Roboto Mono
    features:
        - content.code.copy
        - content.footnote.tooltips
        - navigation.expand
        - navigation.footer
        - navigation.indexes
        - navigation.sections
        - navigation.top
        - search.highlight
        - search.suggest
        - toc.follow

extra_css:
    - assets/css/custom.css

markdown_extensions:
    - abbr
    - attr_list
    - admonition
    - footnotes
    - md_in_html
    - pymdownx.caret
    - pymdownx.emoji
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.tilde
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets:
          check_paths: true
    - pymdownx.superfences
    - toc:
          permalink: "¤"

plugins:
    - search
    - mkdocstrings:
          default_handler: python
          handlers:
              python:
                  paths: [src]
                  inventories:
                      - https://docs.python.org/3/objects.inv
                      # - https://compas.dev/compas/latest/objects.inv
                  options:
                      allow_inspection: true
                      backlinks: tree
                      docstring_options:
                          ignore_init_summary: true
                          trim_doctest_flags: true
                      docstring_style: numpy
                      docstring_section_style: list
                      filters: public
                      group_by_category: true
                      heading_level: 1
                      inherited_members: false
                      line_length: 88
                      merge_init_into_class: true
                      modernize_annotations: true
                      parameter_headings: false
                      preload_modules: [mkdocstrings]
                      relative_crossrefs: true
                      scoped_crossrefs: true
                      separate_signature: true
                      show_bases: false
                      show_category_heading: true
                      show_docstring_attributes: true
                      show_docstring_functions: true
                      show_docstring_modules: false
                      show_if_no_docstring: false
                      show_inheritance_diagram: false
                      show_root_heading: true
                      show_root_full_path: true
                      show_signature: true
                      show_signature_annotations: true
                      show_signature_type_parameters: true
                      show_source: false
                      show_submodules: false
                      show_symbol_type_heading: true
                      show_symbol_type_toc: true
                      signature_crossrefs: true
                      summary:
                          modules: false
                      type_parameter_headings: true
                      unwrap_annotated: true

nav:
    - Introduction: index.md
    - Get Started:
          - Installation: installation.md
          - Remote Viewer: remote.md
          - Shortcuts: shortcuts.md
    - Tutorials:
          - Basic Geometry: tutorials/basic_geometry.md
    - API Reference:
          - Viewer:
                - App: reference/viewer/viewer.md
          - Materials:
                - Generic: reference/materials/generic_material.md
                - Material: reference/materials/material.md
                - Physical Material: reference/materials/physical_material.md
                - Point Material: reference/materials/point_material.md
                - Line Material: reference/materials/line_material.md
          - Lights:
                - Light: reference/lights/light.md
                - Point Light: reference/lights/point_light.md
                - Spot Light: reference/lights/spot_light.md
                - Rect Light: reference/lights/rect_light.md
                - Sky: reference/lights/sky.md
                - Sun: reference/lights/sunlight.md
          - Metadata:
                - Metadata: reference/metadata/metadata.md
          - UI:
                - Button: reference/ui/button.md
                - Slider: reference/ui/slider.md
                - Number Field: reference/ui/number_field.md
          - Text:
                - Text Geometry: reference/text/text.md

    - Other:
          - Changelog: changelog.md
          - License: license.md
